### ISSUE TITLE
Error in glimpse

### ISSUE THREAD

**Issue by Juancortes7** [luifrancgom/marketing_research_and_analytics#4] opened 2024-04-28 16:10 UTC
Buenos días profe

En el desarrollo del capítulo 4 al final de la grabación de abril 24 me genera este error 

![image](https://github.com/luifrancgom/marketing_research_and_analytics/assets/167640974/75d637f1-5730-44a7-850b-51522aa76464)

**Comment by luifrancgom** [comment] 2024-04-28 17:42
Please share a  **Minimal Reproducible Example (MRE)** in relation to the problem you are having as it is mention in the message when you post an issue.

Also specify all the information because I can not help you if you don't show me what you are  doing and how you are doing it.

You need to show me your source code so I can replicate what you are doing.

Also check out that you are loading the `tidyverse` library first. Take into account that when you code the computer run the code sequentially.

For example, this will work:

``` r
# Libraries ----
library(tidyverse)

# Exploring data ----
glimpse(iris)
#> Rows: 150
#> Columns: 5
#> $ Sepal.Length <dbl> 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.…
#> $ Sepal.Width  <dbl> 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.…
#> $ Petal.Length <dbl> 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.…
#> $ Petal.Width  <dbl> 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.…
#> $ Species      <fct> setosa, setosa, setosa, setosa, setosa, setosa, setosa, s…
```

<sup>Created on 2024-04-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

But this will not work if you have not yet loaded the `tidyverse` library:

``` r
# Exploring data ----
glimpse(iris)
#> Error in glimpse(iris): could not find function "glimpse"

# Libraries ----
library(tidyverse)
```

<sup>Created on 2024-04-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Juancortes7** [comment] 2024-04-29 13:42
Yes sr you're right, the problem it's was I didn't run sequentially. So I check the process again and that's works.

A quick question, have you today time for talking about report part 2? I mean for microsoft teams

Thank you so much

**Comment by luifrancgom** [comment] 2024-04-29 14:04
Don't post this here. Just call me or send me an email.

**Comment by Juancortes7** [comment] 2024-04-29 14:11
Ok I sent a e-mail. Thank you

**Comment by luifrancgom** [comment] 2024-07-21 16:59
Problem solve. Closing issue.

**Closed as completed by luifrancgom** 2024-07-21 16:59 UTC
Labels: R question, Quarto question
